salesforce-web-frontend/Models/Lead.cs
namespace salesforce_web_frontend.Models
{
    public class Lead
    {
        public string Firstname { get; set; }

        public string Lastname { get; set; }

        public string Company { get; set; }

        public string Description { get; set; }
    }
}

salesforce-web-frontend/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace salesforce_web_frontend.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

salesforce-web-frontend/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace salesforce_web_frontend.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

salesforce-web-frontend/Pages/Salesforce/LeadForm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using salesforce_web_frontend.Models;
using salesforce_web_frontend.Services;

namespace salesforce_web_frontend.Pages.Salesforce
{
    public class LeadFormModel : PageModel
    {
        public ISalesforceService SalesforceService { get; set; }

        private readonly ILogger<LeadFormModel> _logger;

        public LeadFormModel(ILogger<LeadFormModel> logger, ISalesforceService salesforceService)
        {
            _logger = logger;
            SalesforceService = salesforceService;
        }


        public SalesforceSObjectResponse SalesforceSObjectResponse { get; set; }

        public void OnGet()
        {
        }
        public async Task OnPostSubmit(Lead lead)
        {
            SalesforceSObjectResponse =  await SalesforceService.CreateLeadAsync(lead);

        }
    }
}

salesforce-web-frontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

salesforce-web-frontend/Pages/Salesforce/LeadForm.cshtml
@page
@model salesforce_web_frontend.Pages.Salesforce.LeadFormModel

@if (Model.SalesforceSObjectResponse != null)

{
    <p>Lead was created with ID: @Model.SalesforceSObjectResponse.id</p>


}
else
{
    <form method="post">
        <table>
            <tr>
                <td>Company: </td>
                <td><input type="text" id="Company" name="Company"/></td>
            </tr>
            <tr>
                <td>First Name: </td>
                <td><input type="text" id="Firstname" name="Firstname"/></td>
            </tr>
            <tr>
                <td>Last Name: </td>
                <td><input type="text" id="Lastname" name="Lastname"/></td>
            </tr>
            <tr>
                <td>Description: </td>
                <td><textarea type="text"  id="Description" name="Description"></textarea></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" asp-page-handler="Submit"/></td>
            </tr>
        </table>
        <hr/>
    </form>
}

salesforce-web-frontend/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - salesforce_web_frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">salesforce_web_frontend</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Salesforce/LeadForm">Lead</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - salesforce_web_frontend - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>